export const JOB_CATEGORIES = [
  "Software Development",
  "Data Science",
  "Machine Learning/AI",
  "Web Development",
  "Mobile Development",
  "DevOps/Cloud",
  "UI/UX Design",
  "Project Management",
  "Product Management",
  "QA/Testing",
  "Cybersecurity",
  "Business Intelligence",
  "Technical Writing",
  "Database Administration",
  "Network Engineering",
  "IT Support",
];

export const JOB_ROLES = [
  "Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Mobile Developer",
  "Data Scientist",
  "Data Engineer",
  "Machine Learning Engineer",
  "DevOps Engineer",
  "Cloud Architect",
  "Product Manager",
  "Project Manager",
  "UI/UX Designer",
  "QA Engineer",
  "Technical Writer",
  "Database Administrator",
  "Network Engineer",
  "IT Support Specialist",
  "Cybersecurity Analyst",
  "Business Intelligence Analyst",
];

export const INDUSTRIES = [
  "Technology",
  "Healthcare",
  "Finance",
  "Education",
  "Retail",
  "Manufacturing",
  "Entertainment",
  "Hospitality",
  "Transportation",
  "Energy",
  "Telecommunications",
  "E-commerce",
  "Consulting",
  "Non-profit",
  "Government",
  "Real Estate",
];

export const LOCATIONS = [
  "Remote",
  "New York, NY",
  "San Francisco, CA",
  "Austin, TX",
  "Seattle, WA",
  "Boston, MA",
  "Chicago, IL",
  "Los Angeles, CA",
  "Denver, CO",
  "Atlanta, GA",
  "Washington, DC",
  "London, UK",
  "Toronto, Canada",
  "Berlin, Germany",
  "Paris, France",
  "Amsterdam, Netherlands",
  "Sydney, Australia",
  "Singapore",
  "Bangalore, India",
  "Dublin, Ireland",
  "Tel Aviv, Israel",
];

export const AVAILABILITY_OPTIONS = [
  { value: "immediate", label: "Immediately" },
  { value: "two_weeks", label: "In two weeks" },
  { value: "one_month", label: "In one month" },
  { value: "other", label: "Other (specify in summary)" },
];

export const WORK_TYPE_OPTIONS = [
  { value: "remote", label: "Remote" },
  { value: "hybrid", label: "Hybrid" },
  { value: "on-site", label: "On-site" },
]; 